# Generated by Django 4.2.1 on 2023-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Login', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('IQTestPoints', models.IntegerField(null=True)),
                ('IQTestAnswerTime', models.DateTimeField(null=True)),
                ('EQTestResult', models.CharField(max_length=5, null=True)),
                ('EQTestAnswerTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
